# This config file sets the `noindex` rule for each branch (e.g. [0-17-0]) listed below
# For Netlify instructions, see: https://docs.netlify.com/routing/headers/#custom-headers-for-different-branch-or-deploy-contexts
# For more details about the netlify.toml file, see https://docs.netlify.com/configure-builds/file-based-configuration/
# For _headers file syntax: https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
# For details on Deploy context: https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts

[context.0-17-0]
  command = "yarn build && cp ./custom-headers/_0-17-0 ./build/_headers"

[context.0-16-0]
  command = "yarn build && cp ./custom-headers/_0-16-0 ./build/_headers"

[context.0-15-0]
  command = "yarn build && cp ./custom-headers/_0-15-0 ./build/_headers"

[context.0-14-0]
  command = "yarn build && cp ./custom-headers/_0-14-0 ./build/_headers"

[context.0-13-0]
  command = "yarn build && cp ./custom-headers/_0-13-0 ./build/_headers"

[context.0-12-0]
  command = "yarn build && cp ./custom-headers/_0-12-0 ./build/_headers"

[context.0-11-0]
  command = "yarn build && cp ./custom-headers/_0-11-0 ./build/_headers"

[context.0-10-0]
  command = "yarn build && cp ./custom-headers/_0-10-0 ./build/_headers"

[context.0-9-0]
  command = "yarn build && cp ./custom-headers/_0-9-0 ./build/_headers"

[context.0-8-0]
  command = "yarn build && cp ./custom-headers/_0-8-0 ./build/_headers"

[context.0-7-0]
  command = "yarn build && cp ./custom-headers/_0-7-0 ./build/_headers"

[context.0-6-0]
  command = "yarn build && cp ./custom-headers/_0-6-0 ./build/_headers"

[context.0-5-0]
  command = "yarn build && cp ./custom-headers/_0-5-0 ./build/_headers"

[context.0-4-0]
  command = "yarn build && cp ./custom-headers/_0-4-0 ./build/_headers"

[context.0-3-0]
  command = "yarn build && cp ./custom-headers/_0-3-0 ./build/_headers"

[context.0-2-0]
  command = "yarn build && cp ./custom-headers/_0-2-0 ./build/_headers"

[context.0-1-0]
  command = "yarn build && cp ./custom-headers/_0-1-0 ./build/_headers"

